node ("maven") {

   // download and configure all common cicd stuff
   dir('app') {


      // ===============================================================================
      // SCRIPT Declarations (from OCP 3.6 use the Pipeline BuildConfig ENV Variables)
      // ===============================================================================


      APP_GIT_URL  = "https://github.com/skoussou/multi-xpaas-micros-story.git"
      CONTEXT_PATH = "dm-micro"
      

      APP_TEMPLATE = "dm-micro/openshift/templates/decisions-server64-basic-s2i-template-PAYMENTS-binary.yml"
      //NEXUS_URL = "http://10.25.28.72:8081/repository/maven-releases/"
      NEXUS_URL = "http://nexus-poc.192.168.42.210.nip.io/nexus/content/repositories/releases/"

      APP_NAME = "uaex-rules-api"
      IMAGESTREAM_PROJECT = "poc"

      GROUP_ID = ""
      ARTIFACT_ID = ""
      APP_VERSION= ""
      KIE_CONTAINER_NAME= "payments"

      DEV_PROJECT = "poc"
//      QA_PROJECT = "sos-online-qa"
//      INT_PROJECT = "sos-online-int"
//      STAGE_PROJECT = "sos-online-stage"
//      PROD_PROJECT = "sos-online-prod"

      SETTINGS_XML_NAME= "settings.xml"


      echo '============================================================'
      echo 'Download xPAAS apps and ci/cd required files'

      git branch: "master", url: "${APP_GIT_URL}"

      sh "pwd"
      sh "ls -la"
      echo "${CONTEXT_PATH}/openshift/pipeline/functions/apply-template.groovy"


      //echo "COMMAND PWD"
      //sh "pwd"

      // load openshift-utils functions (using this path as convention.. define a env var if desired...)
      openshiftUtils = load("dm-micro/openshift/pipeline/functions/openshift-utils.groovy")
                             

      // load groovy functions
     // newman = load "dm-micro/openshift/pipeline/functions/openshift-utils.groovy"
      echo '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++'

   }  

   stage("Build & Test KJAR") {

      dir('app') {

          dir ("${CONTEXT_PATH}") {
	         // Build, package, test and deploy with custom settings.xml pointing to corporate NEXUS
                   sh "mvn deploy -s ./openshift/configuration/${SETTINGS_XML_NAME}"

                 // Capture KJAR GAV Details to use for its download from NEXUS
                 // extract info from pom.xml to build NEXUS_ARTIFACT_PATH

                 def pom = readMavenPom file: "pom.xml"
                 APP_VERSION = pom.version
   
                 ARTIFACT_ID = pom.artifactId
                 GROUP_ID = pom.groupId
                 def GROUP_ID_PATH = pom.groupId.replace(".","/")
  
                 // removed as in BRMS it is KJAR
                 //def packaging = pom.packaging
                 def packaging = "jar"
            
                 echo "APP_VERSION = ${APP_VERSION}"
                 echo "ARTIFACT_ID = ${ARTIFACT_ID}"
                 echo "GROUP_ID = ${GROUP_ID}"
                 echo "GROUP_ID_PATH = ${GROUP_ID_PATH}"
                 echo "packaging = ${packaging}"

  
                 NEXUS_ARTIFACT_PATH = "${GROUP_ID_PATH}/${ARTIFACT_ID}/${APP_VERSION}/${ARTIFACT_ID}-${APP_VERSION}.${packaging}"
                 echo "======================================================================================"
                 echo "NEXUS ${APP_NAME} ARTFIFACT Location at ${NEXUS_ARTIFACT_PATH}"
                 echo "======================================================================================"
          }

          stash name: "app-template", includes: "${APP_TEMPLATE }"
      }  
   }

}

node ("nodejs") {


   
   // get app template back
   unstash "app-template" 
   
   stage("Build Rules container") {
      
        // no need to define a cluster if we have just one defined and it is the one where Jenkins is running 
        openshift.withCluster() { 

            //openshift.doAs( 'jenkins' ) {
            //groupId="com/redhat/consulting"
            //artifactId="dm-micro"
            //packaging="jar"

            //echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
            //NEXUS_ARTIFACT_PATH = "${GROUP_ID}/${ARTIFACT_ID}/${APP_VERSION}/${ARTIFACT_ID}-${APP_VERSION}.${packaging}"
            //echo "NEXUS ${APP_NAME} ARTFIFACT Location at ${NEXUS_ARTIFACT_PATH}"
            //echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"

           //CUSTOM_TEMPLATE_PARAMETERS = "-p KIE_CONTAINER_DEPLOYMENT=payments=com.redhat.consulting:dm-micro:1.0.0 -p SOURCE_REPOSITORY_URL=https://github.com/skoussou/multi-xpaas-micros-story.git -p SOURCE_REPOSITORY_REF=master -p CONTEXT_DIR=dm-micro -p appargs=kie.maven.settings.custom=${NEXUS_URL} -p IMAGESTREAM_PROJECT=poc"

          CUSTOM_TEMPLATE_PARAMETERS = "-p KIE_CONTAINER_DEPLOYMENT=${KIE_CONTAINER_NAME}=${GROUP_ID}:${ARTIFACT_ID}:${APP_VERSION} -p SOURCE_REPOSITORY_URL=https://github.com/skoussou/multi-xpaas-micros-story.git -p SOURCE_REPOSITORY_REF=master -p CONTEXT_DIR=dm-micro -p IMAGESTREAM_PROJECT=poc -l app=${APP_NAME}"


     openshiftUtils.applyTemplate("${DEV_PROJECT}", "${APP_TEMPLATE}", "${APP_NAME}", "${APP_VERSION}", "${APP_NAME}", "${CUSTOM_TEMPLATE_PARAMETERS}" , [])
                //openshiftUtils.startBuildFromFile("${DEV_PROJECT}", "${APP_NAME}", "${NEXUS_URL}${NEXUS_ARTIFACT_PATH}", true) 
     openshiftUtils.startBuildFromFile("${DEV_PROJECT}", "${APP_NAME}", "${NEXUS_URL}${NEXUS_ARTIFACT_PATH}", true) 
            //}
        }
   }


   stage("Deploy Rules ${DEV_PROJECT} Project") {

     // openshift.withCluster() { 
    //     openshiftUtils.deploy("${DEV_PROJECT}", "${APP_NAME}")
     // } 
  }
}
