node ("jenkins-slave-nodejs8-maven") {

   // download and configure all common cicd stuff
   dir('app') {

      // ===============================================================================
      // SCRIPT Declarations (from OCP 3.6 use the Pipeline BuildConfig ENV Variables)
      // ===============================================================================


      APP_GIT_URL  = "https://github.com/skoussou/multi-xpaas-micros-story.git"
      APP_GIT_REPO_BRANCH = "master"
      CONTEXT_PATH = "angular-bpms-app"

      APP_TEMPLATE = "../openshift/templates/eap-ui-web-angular-template.yml"

      //MAVEN_MIRROR_URL = "http://10.25.28.72:8081/repository/maven-public/"
      NEXUS_URL = "http://nexus-poc.192.168.42.210.nip.io/nexus/content/repositories/releases/"

      APP_NAME = "uaex-payments-ui"
      IMAGESTREAM_PROJECT = "poc"

      DEV_PROJECT = "poc"
//      QA_PROJECT = "sos-online-qa"
//      INT_PROJECT = "sos-online-int"
//      STAGE_PROJECT = "sos-online-stage"
//      PROD_PROJECT = "sos-online-prod"

      SETTINGS_XML_NAME= "settings.xml"


      CUSTOM_TEMPLATE_PARAMETERS = "-p SOURCE_REPOSITORY_URL=${APP_GIT_URL} -p SOURCE_REPOSITORY_REF=${APP_GIT_REPO_BRANCH} -p CONTEXT_DIR=${CONTEXT_PATH} -p appargs=kie.maven.settings.custom=${NEXUS_URL} -p REGISTRY=172.30.190.52:5000 -p IMAGESTREAM_PROJECT=sos-online-dev"


      echo '============================================================'
      echo 'Download xPAAS apps and ci/cd required files'

      git branch: "${APP_GIT_REPO_BRANCH}", url: "${APP_GIT_URL}"

      // load openshift-utils functions (using this path as convention.. define a env var if desired...)
      openshiftUtils = load("dm-micro/openshift/pipeline/functions/openshift-utils.groovy")
                             

      // load groovy functions
     // newman = load "dm-micro/openshift/pipeline/functions/openshift-utils.groovy"
      echo '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++'

   }  


   stage("Clone & Build Web App") {

      dir('app') {

          dir ("${CONTEXT_PATH}") {
	         // Build, package, test and deploy with custom settings.xml pointing to corporate NEXUS
                   sh "/usr/local/maven/bin/mvn deploy -s ./openshift/configuration/${SETTINGS_XML_NAME}"

                 // Capture KJAR GAV Details to use for its download from NEXUS
                 // extract info from pom.xml to build NEXUS_ARTIFACT_PATH

                 def pom = readMavenPom file: "pom.xml"
                 APP_VERSION = pom.version
   
                 ARTIFACT_ID = pom.artifactId
                 GROUP_ID = pom.groupId
                 def GROUP_ID_PATH = pom.groupId.replace(".","/")
  
                 // removed as in BRMS it is KJAR
                 def packaging = pom.packaging
                 //def packaging = "jar"
            
                 echo "APP_VERSION = ${APP_VERSION}"
                 echo "ARTIFACT_ID = ${ARTIFACT_ID}"
                 echo "GROUP_ID = ${GROUP_ID}"
                 echo "GROUP_ID_PATH = ${GROUP_ID_PATH}"
                 echo "packaging = ${packaging}"

  
                 NEXUS_ARTIFACT_PATH = "${GROUP_ID_PATH}/${ARTIFACT_ID}/${APP_VERSION}/${ARTIFACT_ID}-${APP_VERSION}.${packaging}"
                 echo "======================================================================================"
                 echo "NEXUS ${APP_NAME} ARTFIFACT Location at ${NEXUS_ARTIFACT_PATH}"
                 echo "======================================================================================"
          }

          stash name: "app-template", includes: "${APP_TEMPLATE }"
      }  

   }


   stage("Push Artifact to Nexus") {

   }






}
