apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"build.openshift.io/v1","kind":"BuildConfig","metadata":{"annotations":{},"name":"fis-rest-1-pipeline","namespace":"poc"},"spec":{"nodeSelector":{},"output":{},"postCommit":{},"resources":{},"runPolicy":"Serial","source":{"git":{"ref":"master","uri":"https://github.com/skoussou/multi-xpaas-micros-story.git"},"type":"Git"},"strategy":{"jenkinsPipelineStrategy":{"jenkinsfilePath":"fis-rest-1/Jenkinsfile"},"type":"JenkinsPipeline"},"triggers":[]}}
  creationTimestamp: null
  name: fis-rest-1-pipeline
spec:
  nodeSelector: {}
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: https://github.com/rahmed-rh/uaex-fis-1.git
    type: Git
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
    type: JenkinsPipeline
  triggers: []
status:
  lastVersion: 0
