node ("maven") {

   // download and configure all common cicd stuff
   dir('app') {

      // ===============================================================================
      // SCRIPT Declarations (from OCP 3.6 use the Pipeline BuildConfig ENV Variables)
      // ===============================================================================


      APP_GIT_URL  = "https://github.com/skoussou/multi-xpaas-micros-story.git"


      APP_TEMPLATE = "../openshift/templates/processserver64-mysql-s2i-protected-scm-ocp-no-probe-binary-build.yml"
      NEXUS_URL = "http://nexus.sos.eu/content/repositories/redhat-internal-dev-demo-release"
      //NEXUS_URL = "http://nexus.sos.eu/content/groups/redhat-internal"
      DEV_PROJECT = "sos-online-dev"
      QA_PROJECT = "sos-online-qa"
      INT_PROJECT = "sos-online-int"
      STAGE_PROJECT = "sos-online-stage"
      PROD_PROJECT = "sos-online-prod"
      APP_NAME = "kieserver"
      IMAGESTREAM_PROJECT = "sos-online-dev"
      CUSTOM_TEMPLATE_PARAMETERS = "-p KIE_CONTAINER_DEPLOYMENT=sosonlinedoctor=com.sos:sos-online-workflows:1.0.0 -p SOURCE_REPOSITORY_URL=https://gitlab.consulting.redhat.com/sos/isp-processes.git -p HTTPS_PASSWORD=ocppass -p HTTPS_KEYSTORE=sso-https.jks -p SOURCE_REPOSITORY_REF=master -p CONTEXT_DIR='' -p appargs=kie.maven.settings.custom=${NEXUS_URL} -p REGISTRY=172.30.190.52:5000 -p IMAGESTREAM_PROJECT=sos-online-dev"



      echo '============================================================'
      echo 'Download xPAAS apps and ci/cd required files'
      //  git branch: "master", credentialsId: "sos-online-utilities-gitlabcredentials", url: "${APP_GIT_URL}"

       git branch: "master", url: "${APP_GIT_URL}"

      //echo "COMMAND PWD"
      //sh "pwd"

      echo "COMMANDA ls -la"
      //sh "ls -la"
      sh "ls angular-bpms-app/openshift/pipeline/functions"


      // load openshift-utils functions (using this path as convention.. define a env var if desired...)
      openshiftUtils = load 'angular-bpms-app/openshift/pipeline/functions/openshift-utils.groovy'
                             

      // load groovy functions
      newman = load 'angular-bpms-app/openshift/pipeline/functions/newman.groovy'
      echo '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++'

   }  
   // define maven with custom settings.xml (using this path as convention.. define a env var if desired...)in
   //def mvnCmd = "mvn -s ${WORKSPACE}/cicd/maven/settings.xml" 

   stage("Build Image with NPM (Optional)") {

   }

}
