metadata:
  labels:
    app: uaex-fis-2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: uaex-fis-2
    spec:
      containers:
        - 
          resources:
            requests:
              cpu: 
              memory: 
            limits:
              cpu: 
              memory: 512Mi
          env:
          - name: KIE_SERVICE_NAME
            value: uaex-rules-api
          - name: KIE_SERVICE_PORT
            value: 8080
          - name: KIE_CONTAINER
            value: payments
          - name: KIE_SERVICE_USERNAME
            value: kieserver
          - name: KIE_SERVICE_PASSWORD
            value: kieserver123!
          - name: ACTIVEMQ_SERVICE_NAME
            value: broker-uaex-amq-tcp
          - name: ACTIVEMQ_SERVICE_PORT
            value: 61616
          - name: ACTIVEMQ_BROKER_USERNAME
            value: admin
          - name: ACTIVEMQ_BROKER_PASSWORD
            value: passw0rd
          - name: ACTIVEMQ_POOL_MAX_CONNECTIONS
            value: 10
          - name: JAVA_DIAGNOSTICS
            value: true
