apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    application: payments-ui
  name: payments-ui
spec:
  replicas: 1
  selector:
    deploymentConfig: payments-ui
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        application: payments-ui
        deploymentConfig: payments-ui
      name: payments-ui
    spec:
      containers:
      - env:
        - name: JGROUPS_PING_PROTOCOL
          value: openshift.DNS_PING
        - name: OPENSHIFT_DNS_PING_SERVICE_NAME
          value: payments-ui-ping
        - name: OPENSHIFT_DNS_PING_SERVICE_PORT
          value: "8888"
        - name: MQ_CLUSTER_PASSWORD
          value: 324324sca
        - name: MQ_QUEUES
          value: someque
        - name: MQ_TOPICS
          value: sometopic
        - name: JGROUPS_CLUSTER_PASSWORD
          value: dfa223few
        image: payments-ui
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - /opt/eap/bin/livenessProbe.sh
          initialDelaySeconds: 60
        name: payments-ui
        ports:
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8888
          name: ping
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - /opt/eap/bin/readinessProbe.sh
        resources:
          limits:
            memory: 1Gi
      terminationGracePeriodSeconds: 75
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - payments-ui
      from:
        kind: ImageStreamTag
        name: payments-ui:1.0.0
    type: ImageChange
  - type: ConfigChange
