# PAYMENTS UI

## Create Binary from Source
[source,bash]
----
cd payments-ui
mvn clean install
----

## Create Build

[source,bash]
----
oc login https://[OCP-CLUSTER-DOMAIN]:443 -u USERNAME -p PASSWORD
oc new-build --binary=true --image-stream=jboss-eap71-openshift:1.2 --name=payments-ui --allow-missing-images
oc start-build payments-ui --from-file=[PATH-TO-LOCAL-GIT-DIR]/multi-xpaas-micros-story/payments-ui/target/payments-ui.war
----


## Create Deployment Config

create PAYMENTS-UI deployment with the DeploymentConfig

* Option 1 - go to Cluster console, changet to project and "Add to project" --> YAML --> copy paste the following deployment source
* Option 2 - Logged in to OCP Cluster and on the project you wish the deployment to be created execute *oc create -f PATH-TO-LOCAL-GIT-DIR]/multi-xpaas-micros-story/payments-ui/openshift/templates/payments-ui-deployment-config.yml*

[source,bash]
----
apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    application: payments-ui
  name: payments-ui
spec:
  replicas: 1
  selector:
    deploymentConfig: payments-ui
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        application: payments-ui
        deploymentConfig: payments-ui
      name: payments-ui
    spec:
      containers:
      - env:
        - name: JGROUPS_PING_PROTOCOL
          value: openshift.DNS_PING
        - name: OPENSHIFT_DNS_PING_SERVICE_NAME
          value: payments-ui-ping
        - name: OPENSHIFT_DNS_PING_SERVICE_PORT
          value: "8888"
        - name: MQ_CLUSTER_PASSWORD
          value: 324324sca
        - name: MQ_QUEUES
          value: someque
        - name: MQ_TOPICS
          value: sometopic
        - name: JGROUPS_CLUSTER_PASSWORD
          value: dfa223few
        image: payments-ui
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - /opt/eap/bin/livenessProbe.sh
          initialDelaySeconds: 60
        name: payments-ui
        ports:
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8888
          name: ping
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - /opt/eap/bin/readinessProbe.sh
        resources:
          limits:
            memory: 1Gi
      terminationGracePeriodSeconds: 75
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - payments-ui
      from:
        kind: ImageStreamTag
        name: payments-ui:1.0.0
    type: ImageChange
  - type: ConfigChange
----

## Create Service



create PAYMENTS-UI Service for http & ping with following config

* Option 1 - go to Cluster console, changet to project and "Add to project" --> YAML --> copy paste the following deployment source
* Option 2 - Logged in to OCP Cluster and on the project you wish the deployment to be created execute *oc create -f PATH-TO-LOCAL-GIT-DIR]/multi-xpaas-micros-story/payments-ui/openshift/templates/payments-ui-service-config.yml*

[source,bash]
----
apiVersion: v1
kind: Service
metadata:
  annotations:
    description: The web server's http port.
  labels:
    application: ${APPLICATION_NAME}
  name: ${APPLICATION_NAME}
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    deploymentConfig: ${APPLICATION_NAME}
apiVersion: v1
kind: Service
metadata:
  annotations:
    description: The JGroups ping port for clustering.
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  labels:
    application: ${APPLICATION_NAME}
  name: ${APPLICATION_NAME}-ping
spec:
  clusterIP: None
  ports:
  - name: ping
    port: 8888
  selector:
    deploymentConfig: ${APPLICATION_NAME}
----


## Create Service Route

for now via the UI



## PAYMENTS UI

### Payees

### Bill Payments

### Kie COntainers

