kind: BuildConfig
apiVersion: v1
metadata:
  name: uaex-payments-rules-pipeline
spec:
  source:
    git:
      uri: https://github.com/skoussou/multi-xpaas-micros-story.git
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath:  dm-micro/openshift/pipeline/Jenkinsfile

